### ISSUE TITLE
Could not find de.idnow.sdk:idnow-android-3.21.0:.

### ISSUE THREAD

**Issue by nitishlovesandroid** [bitwala/react-native-idnow#12] opened 2020-02-19 07:33 UTC
Could not find de.idnow.sdk:idnow-android-3.21.0:.

**Comment by NazarYablonskiy** [comment] 2020-03-13 09:57
Thank you @nitishlovesandroid for reporting!
Could you try the newest version and provide more info if the issue is still there?

**Comment by NazarYablonskiy** [comment] 2020-04-03 10:33
Must be fixed now.
@nitishlovesandroid feel free to re-open.

**Closed by NazarYablonskiy** 2020-04-03 10:33 UTC
